version: "3.8"

services:
  app:
    build:
      context: .
    env_file:
      - .env
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    depends_on:
      - db
  db:
    image: mysql:5.7.40
    environment:
      MYSQL_DATABASE: oc
      MYSQL_ROOT_PASSWORD: 123test
    volumes:
      - data:/var/lib/mysql
  nginx:
    image: nginx:1.17-alpine
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
volumes:
  data: